CC = g++
CFLAGS = -std=c++20 -Wall
TARGET = program

${TARGET}:
	${CC} ${CFLAGS} memory.cpp main.cpp -o ${TARGET}
	${TARGET}

# default
# (01) g++ -std=c++20 -Wall main.cpp -o program
# (02) g++ -std=c++20 -Wall memory.cpp main.cpp -o program
